application: python-simple
version: 1
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- channel_presence

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.(gif|jpg|js|css))
  static_files: \1
  upload: (.*\.(gif|jpg|js|css))

- url: /(.*\.html)
  static_files: pages/\1
  upload: pages/(.*\.html)

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
